### ISSUE TITLE
oersted create_view doesn't work in 6.0

### ISSUE THREAD

**Issue by kryskool** [kryskool/oersted#1]
> > > View = oeclient.create_view('demo','account.view_account_analytic_account_form')
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/oersted/client.py", line 212, in create_view
> > >     data_id = data_obj._get_id(module, view_name)
> > >   File "/usr/local/lib/python2.7/dist-packages/oersted/client.py", line 70, in proxy
> > >     return self.cnx.receive()
> > >   File "/usr/local/lib/python2.7/dist-packages/oersted/oesocket.py", line 58, in receive
> > >     raise ERPError(obj, err)
> > > oersted.oesocket.ERPError: warning -- Access Denied

Private methods (such as _get_id) cannot be called remotely.

**Comment by kryskool** [comment]
In 6.0 we cannot use method private in XMLRPC and NETRPC
Use get_object_reference() instead of _get_id
